name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    continue-on-error: True
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - uses: pre-commit/action@v3.0.0
    - name: Install dependencies
      run:  pip install poetry tox
    - name: Check Poetry lock file
      run: make poetry-lock-check
    - name: Code style check
      run: |
        tox -e ruff-format,ruff-check,vulture
    - name: Static type check
      run: tox -e mypy
    - name: Check copyright
      run: tox -e check-copyright
    - name: Misc checks
      run: tox -e bandit,safety
